<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE tms_config [
<!ELEMENT tms_config (corridor | camera | commlink | controller | dms)*>
<!ATTLIST tms_config time_stamp CDATA #REQUIRED>
<!ELEMENT corridor (r_node)*>
<!ATTLIST corridor route CDATA #REQUIRED>
<!ATTLIST corridor dir CDATA #REQUIRED>
<!ELEMENT r_node (detector | meter)*>
<!ATTLIST r_node name CDATA #REQUIRED>
<!ATTLIST r_node n_type CDATA 'Station'>
<!ATTLIST r_node pickable CDATA 'f'>
<!ATTLIST r_node above CDATA 'f'>
<!ATTLIST r_node transition CDATA 'None'>
<!ATTLIST r_node station_id CDATA #IMPLIED>
<!ATTLIST r_node label CDATA ''>
<!ATTLIST r_node lon CDATA #REQUIRED>
<!ATTLIST r_node lat CDATA #REQUIRED>
<!ATTLIST r_node lanes CDATA '0'>
<!ATTLIST r_node attach_side CDATA 'right'>
<!ATTLIST r_node shift CDATA '0'>
<!ATTLIST r_node active CDATA 't'>
<!ATTLIST r_node s_limit CDATA '55'>
<!ATTLIST r_node forks CDATA #IMPLIED>
<!ELEMENT detector EMPTY>
<!ATTLIST detector name CDATA #REQUIRED>
<!ATTLIST detector label CDATA 'FUTURE'>
<!ATTLIST detector abandoned CDATA 'f'>
<!ATTLIST detector category CDATA ''>
<!ATTLIST detector lane CDATA '0'>
<!ATTLIST detector field CDATA '22.0'>
<!ATTLIST detector controller CDATA #IMPLIED>
<!ELEMENT meter EMPTY>
<!ATTLIST meter name CDATA #REQUIRED>
<!ATTLIST meter lon CDATA #IMPLIED>
<!ATTLIST meter lat CDATA #IMPLIED>
<!ATTLIST meter storage CDATA #REQUIRED>
<!ATTLIST meter max_wait CDATA '240'>
<!ELEMENT camera EMPTY>
<!ATTLIST camera name CDATA #REQUIRED>
<!ATTLIST camera description CDATA #REQUIRED>
<!ATTLIST camera lon CDATA #IMPLIED>
<!ATTLIST camera lat CDATA #IMPLIED>
<!ELEMENT commlink EMPTY>
<!ATTLIST commlink name CDATA #REQUIRED>
<!ATTLIST commlink description CDATA #REQUIRED>
<!ATTLIST commlink protocol CDATA #REQUIRED>
<!ELEMENT controller EMPTY>
<!ATTLIST controller name CDATA #REQUIRED>
<!ATTLIST controller active CDATA #REQUIRED>
<!ATTLIST controller drop CDATA #REQUIRED>
<!ATTLIST controller commlink CDATA #IMPLIED>
<!ATTLIST controller lon CDATA #IMPLIED>
<!ATTLIST controller lat CDATA #IMPLIED>
<!ATTLIST controller location CDATA #REQUIRED>
<!ATTLIST controller cabinet CDATA #IMPLIED>
<!ATTLIST controller notes CDATA #IMPLIED>
<!ELEMENT dms EMPTY>
<!ATTLIST dms name CDATA #REQUIRED>
<!ATTLIST dms description CDATA #REQUIRED>
<!ATTLIST dms lon CDATA #IMPLIED>
<!ATTLIST dms lat CDATA #IMPLIED>
]>
<tms_config time_stamp='Fri Mar 30 20:00:02 CDT 2012'>
<corridor route='I-94' dir='WB'>
  <r_node name='rnd_88849' lon='-92.76532' lat='44.96266' lanes='3' shift='5' s_limit='65'/>
  <r_node name='rnd_90769' n_type='Exit' transition='Leg' label='T.H.95' lon='-92.76994' lat='44.96253' lanes='1' shift='5'/>
  <r_node name='rnd_90271' station_id='S1359' label='T.H.95' lon='-92.7721' lat='44.96221' lanes='3' shift='5' s_limit='65'>
    <detector name='6000' label='94/TH95W1' lane='1' controller='ctl_68580'/>
    <detector name='6001' label='94/TH95W2' lane='2' controller='ctl_68580'/>
    <detector name='6002' label='94/TH95W3' lane='3' controller='ctl_68580'/>
  </r_node>
  <r_node name='rnd_90767' n_type='Entrance' transition='Leg' label='T.H.95' lon='-92.77706' lat='44.96112' lanes='1' shift='5'/>
  <r_node name='rnd_90269' station_id='S1360' label='Co Rd 21' lon='-92.7996' lat='44.95411' lanes='3' shift='5' s_limit='65'>
    <detector name='6003' label='94/CR21W1' lane='1' controller='ctl_68579'/>
    <detector name='6004' label='94/CR21W2' lane='2' controller='ctl_68579'/>
    <detector name='6005' label='94/CR21W3' lane='3' controller='ctl_68579'/>
  </r_node>
  <r_node name='rnd_89' lon='-92.81813' lat='44.94957' lanes='3' shift='5' s_limit='65'/>
  <r_node name='rnd_90267' station_id='S1361' label='Co Rd 71' lon='-92.8414' lat='44.94879' lanes='3' shift='5' s_limit='65'>
    <detector name='6006' label='94/CR71W1' lane='1' controller='ctl_68578'/>
    <detector name='6007' label='94/CR71W2' lane='2' controller='ctl_68578'/>
    <detector name='6008' label='94/CR71W3' lane='3' controller='ctl_68578'/>
  </r_node>
  <r_node name='rnd_88851' n_type='Exit' transition='Leg' label='Manning Ave' lon='-92.85762' lat='44.94886' lanes='1' shift='5'>
    <detector name='5100' label='94/ManngWX' category='X' controller='ctl_60812'/>
  </r_node>
  <r_node name='rnd_88853' station_id='S1058' label='Manning Ave' lon='-92.86587' lat='44.94888' lanes='3' shift='5' s_limit='65'>
    <detector name='5101' label='94/ManngW1' lane='1' field='23.0' controller='ctl_60812'/>
    <detector name='5102' label='94/ManngW2' lane='2' field='28.0' controller='ctl_60812'/>
    <detector name='5103' label='94/ManngW3' lane='3' field='25.0' controller='ctl_60812'/>
  </r_node>
  <r_node name='rnd_88855' n_type='Entrance' transition='Leg' label='Manning Ave' lon='-92.86786' lat='44.94886' lanes='1' shift='5'>
    <detector name='5104' label='94/ManngWM' category='M' controller='ctl_60812'/>
  </r_node>
  <r_node name='rnd_88857' station_id='S1059' label='Co Rd 17B' lon='-92.88364' lat='44.94883' lanes='3' shift='5' s_limit='65'>
    <detector name='5105' label='94/CR17BW1' lane='1' field='30.0' controller='ctl_60811'/>
    <detector name='5106' label='94/CR17BW2' lane='2' field='32.3' controller='ctl_60811'/>
    <detector name='5107' label='94/CR17BW3' lane='3' field='23.6' controller='ctl_60811'/>
  </r_node>
  <r_node name='rnd_88859' n_type='Exit' transition='Leg' label='Co Rd 19' lon='-92.89653' lat='44.949' lanes='1' shift='5'>
    <detector name='5108' label='94/CR19WX' category='X' controller='ctl_60810'/>
  </r_node>
  <r_node name='rnd_88861' station_id='S1060' label='Co Rd 19' lon='-92.90236' lat='44.94902' lanes='3' shift='5' s_limit='65'>
    <detector name='5109' label='94/CR19W1' lane='1' field='42.0' controller='ctl_60810'/>
    <detector name='5110' label='94/CR19W2' lane='2' field='32.0' controller='ctl_60810'/>
    <detector name='5111' label='94/CR19W3' lane='3' field='24.0' controller='ctl_60810'/>
  </r_node>
  <r_node name='rnd_88863' n_type='Entrance' transition='Leg' label='Co Rd 19' lon='-92.90749' lat='44.9488' lanes='1' shift='5'>
    <detector name='5112' label='94/CR19WM' category='M' controller='ctl_60810'/>
  </r_node>
  <r_node name='rnd_88865' n_type='Exit' transition='Leg' label='Co Rd 13' lon='-92.9276' lat='44.94893' lanes='1' shift='5'>
    <detector name='5118' label='94/CR13WX' category='X' controller='ctl_60809'/>
  </r_node>
  <r_node name='rnd_88867' station_id='S1061' label='Co Rd 13' lon='-92.92945' lat='44.94893' lanes='3' shift='5' s_limit='65'>
    <detector name='5114' label='94/CR13W1' lane='1' field='38.2' controller='ctl_60809'/>
    <detector name='5115' label='94/CR13W2' lane='2' field='30.0' controller='ctl_60809'/>
    <detector name='5116' label='94/CR13W3' lane='3' field='24.7' controller='ctl_60809'/>
  </r_node>
  <r_node name='rnd_731' lon='-92.93328' lat='44.94891' lanes='4' shift='6'/>
  <r_node name='rnd_90835' n_type='Entrance' transition='Loop' label='Co Rd 13' lon='-92.93349' lat='44.94892' lanes='1' shift='7'>
    <detector name='5119' label='94/CR13WM' category='M' controller='ctl_60809'/>
  </r_node>
  <r_node name='rnd_716' label='W of Co Rd 13' lon='-92.9397' lat='44.94867' lanes='5' shift='7'/>
  <r_node name='rnd_90829' n_type='Exit' transition='CD' label='I-94 CD WB' lon='-92.95037' lat='44.94876' lanes='2' shift='5' forks='rnd_90831'/>
  <r_node name='rnd_95185' station_id='S1062' label='E Jct I-494' lon='-92.95829' lat='44.94877' lanes='3' shift='5'>
    <detector name='5134' label='94/Ej494W1' lane='1'/>
    <detector name='5135' label='94/Ej494W2' lane='2'/>
    <detector name='7038' label='94/Ej494W3' lane='3'/>
  </r_node>
  <r_node name='rnd_88869' n_type='Entrance' transition='CD' label='I-94 CD WB' lon='-92.9684' lat='44.94875' lanes='1' shift='6'/>
  <r_node name='rnd_88873' station_id='S1063' label='W of I-494 E Jct' lon='-92.97177' lat='44.94867' lanes='4' shift='6'>
    <detector name='5136' label='94/W494EJWA1' category='A' lane='1' controller='ctl_2027'/>
    <detector name='5137' label='94/W494EJW2' lane='2' field='25.3' controller='ctl_2027'/>
    <detector name='5138' label='94/W494EJW3' lane='3' field='29.0' controller='ctl_2027'/>
    <detector name='5139' label='94/W494EJWA4' category='A' lane='4' controller='ctl_2027'/>
  </r_node>
  <r_node name='rnd_88835' n_type='Exit' transition='Leg' label='T.H.120' lon='-92.9833' lat='44.94854' lanes='1' shift='5'>
    <detector name='5140' label='94/TH120WX' category='X' controller='ctl_2028'/>
  </r_node>
  <r_node name='rnd_88875' station_id='S1064' label='T.H.120' lon='-92.98462' lat='44.94855' lanes='3' shift='5'>
    <detector name='5141' label='94/TH120W1' lane='1' field='25.5' controller='ctl_2028'/>
    <detector name='5142' label='94/TH120W2' lane='2' field='26.1' controller='ctl_2028'/>
    <detector name='5153' label='94/TH120W3' lane='3' field='25.2' controller='ctl_2028'/>
  </r_node>
  <r_node name='rnd_88833' n_type='Exit' transition='Leg' label='Hudson Rd' lon='-92.98892' lat='44.94855' lanes='1' shift='5'>
    <detector name='5143' label='94/HdsnRdWX' category='X' controller='ctl_2028'/>
  </r_node>
  <r_node name='rnd_717' label='E of Hudson Rd' lon='-92.99238' lat='44.94874' lanes='3' shift='5'/>
  <r_node name='rnd_88831' n_type='Entrance' transition='Leg' label='Hudson Rd' lon='-92.99639' lat='44.94932' lanes='1' shift='5'>
    <detector name='5144' label='94/HdsnRdWM2' category='M' lane='2' controller='ctl_2029'/>
  </r_node>
  <r_node name='rnd_88829' station_id='S1065' label='Hudson Rd' lon='-92.99909' lat='44.94971' lanes='3' shift='5'>
    <detector name='5145' label='94/HdsnRdW1' lane='1' field='23.0' controller='ctl_2029'/>
    <detector name='5146' label='94/HdsnRdW2' lane='2' field='26.5' controller='ctl_2029'/>
    <detector name='5148' label='94/HdsnRdW3' lane='3' field='24.3' controller='ctl_2029'/>
  </r_node>
  <r_node name='rnd_88827' n_type='Entrance' transition='Leg' label='Hudson Rd' lon='-93.00079' lat='44.94995' lanes='1' shift='5'>
    <detector name='5147' label='94/HdsnRdWM1' category='M' lane='1' controller='ctl_2029'/>
  </r_node>
  <r_node name='rnd_88825' station_id='S1066' label='McKnight Rd' lon='-93.00641' lat='44.95058' lanes='3' shift='5'>
    <detector name='5052' label='94/McKngtW1' lane='1' field='26.0' controller='ctl_2030'/>
    <detector name='5053' label='94/McKngtW2' lane='2' field='27.3' controller='ctl_2030'/>
    <detector name='5054' label='94/McKngtW3' lane='3' field='21.0' controller='ctl_2030'/>
  </r_node>
  <r_node name='rnd_88823' n_type='Entrance' transition='Leg' label='McKnight Rd' lon='-93.00895' lat='44.95088' lanes='1' shift='5'>
    <detector name='4926' label='94/McKngtWG' category='G'/>
    <detector name='5149' label='94/McKngtWM' category='M' controller='ctl_2030'/>
    <meter name='M94W28' storage='1'/>
  </r_node>
  <r_node name='rnd_718' label='Ruth St' lon='-93.0151' lat='44.95158' lanes='3' shift='5'/>
  <r_node name='rnd_88821' station_id='S1067' label='Ruth St' lon='-93.01782' lat='44.95173' lanes='3' shift='5'>
    <detector name='5150' label='94/RuthW1' lane='1' field='55.0' controller='ctl_60782'/>
    <detector name='5151' label='94/RuthW2' lane='2' field='57.0' controller='ctl_60782'/>
    <detector name='5152' label='94/RuthW3' lane='3' field='59.0' controller='ctl_60782'/>
  </r_node>
  <r_node name='rnd_88819' n_type='Entrance' transition='Leg' label='Ruth St' lon='-93.01945' lat='44.95165' lanes='1' shift='5'>
    <detector name='4927' label='94/RuthWG' category='G'/>
    <detector name='5154' label='94/RuthWM' category='M' controller='ctl_60782'/>
    <meter name='M94W29' storage='1'/>
  </r_node>
  <r_node name='rnd_88817' n_type='Exit' transition='Leg' label='White Bear Ave' lon='-93.02278' lat='44.95142' lanes='1' shift='5'>
    <detector name='5155' label='94/WhitBrWX' category='X' controller='ctl_60783'/>
  </r_node>
  <r_node name='rnd_88815' station_id='S1068' label='White Bear Ave' lon='-93.02552' lat='44.95144' lanes='3' shift='5'>
    <detector name='5156' label='94/WhitBrW1' lane='1' controller='ctl_60783'/>
    <detector name='5157' label='94/WhitBrW2' lane='2' field='26.5' controller='ctl_60783'/>
    <detector name='5158' label='94/WhitBrW3' lane='3' field='28.0' controller='ctl_60783'/>
  </r_node>
  <r_node name='rnd_88813' n_type='Entrance' transition='Leg' label='White Bear Ave' lon='-93.02745' lat='44.95151' lanes='1' shift='5'>
    <detector name='4928' label='94/WhitBrWG' category='G'/>
    <detector name='5159' label='94/WhitBrWP' category='P' controller='ctl_60783'/>
    <meter name='M94W30' storage='1'/>
  </r_node>
  <r_node name='rnd_88811' n_type='Exit' transition='Leg' label='T.H.61' lon='-93.0354' lat='44.95245' lanes='1' shift='5'>
    <detector name='5160' label='94/TH61WX' category='X' controller='ctl_60784'/>
  </r_node>
  <r_node name='rnd_88809' station_id='S1069' label='T.H.61' lon='-93.03929' lat='44.95278' lanes='3' shift='5'>
    <detector name='5161' label='94/TH61W1' lane='1' field='24.5' controller='ctl_60784'/>
    <detector name='5162' label='94/TH61W2' lane='2' field='24.4' controller='ctl_60784'/>
    <detector name='5163' label='94/TH61W3' lane='3' field='21.5' controller='ctl_60784'/>
  </r_node>
  <r_node name='rnd_719' label='T.H.61' lon='-93.04184' lat='44.95284' lanes='3' shift='5'/>
  <r_node name='rnd_88807' n_type='Entrance' transition='Leg' label='T.H.61 NB' lon='-93.047' lat='44.95245' lanes='2' shift='7'>
    <detector name='5164' label='94/NBTH61WM1' category='M' lane='1' controller='ctl_60784'/>
    <detector name='5165' label='94/NBTH61WM2' category='M' lane='2' controller='ctl_60784'/>
  </r_node>
  <r_node name='rnd_88805' station_id='S1070' label='Johnson Pkwy' lon='-93.05166' lat='44.95201' lanes='5' shift='7'>
    <detector name='5171' label='94/JnsnPkWA1' category='A' lane='1' field='21.0' controller='ctl_60785'/>
    <detector name='5172' label='94/JnsnPkWA2' category='A' lane='2' controller='ctl_60785'/>
    <detector name='5173' label='94/JnsnPkW3' lane='3' field='26.0' controller='ctl_60785'/>
    <detector name='5174' label='94/JnsnPkW4' lane='4' field='25.5' controller='ctl_60785'/>
    <detector name='5175' label='94/JnsnPkW5' lane='5' field='24.0' controller='ctl_60785'/>
  </r_node>
  <r_node name='rnd_720' label='E of Mounds Blvd' lon='-93.05781' lat='44.95188' lanes='5' shift='7'/>
  <r_node name='rnd_87205' n_type='Exit' transition='Leg' label='Mounds Blvd' lon='-93.06737' lat='44.95208' lanes='2' shift='5'>
    <detector name='3241' label='94/MoundsWX1' category='X' lane='1' controller='ctl_60415'/>
    <detector name='3242' label='94/MoundsWX2' category='X' lane='2' controller='ctl_60415'/>
  </r_node>
  <r_node name='rnd_87207' station_id='S792' label='Mounds Blvd' lon='-93.06805' lat='44.95211' lanes='3' shift='5'>
    <detector name='3238' label='94/MoundsW1' lane='1' field='22.4' controller='ctl_60415'/>
    <detector name='3239' label='94/MoundsW2' lane='2' field='21.6' controller='ctl_60415'/>
    <detector name='3240' label='94/MoundsW3' lane='3' field='20.5' controller='ctl_60415'/>
  </r_node>
  <r_node name='rnd_676' label='Mounds Blvd' lon='-93.06932' lat='44.95226' lanes='3' shift='5'/>
  <r_node name='rnd_91430' label='Mounds Blvd' lon='-93.07068' lat='44.9527' lanes='3' shift='5'/>
  <r_node name='rnd_91428' label='Kellogg Blvd' lon='-93.07384' lat='44.95507' lanes='3' shift='5'/>
  <r_node name='rnd_87209' n_type='Exit' transition='Leg' label='I-94 CD WB' lon='-93.07543' lat='44.95532' lanes='1' attach_side='left' shift='2' forks='rnd_91051'/>
  <r_node name='rnd_87213' station_id='S791' label='Kellogg Blvd' lon='-93.07585' lat='44.9553' lanes='3' shift='5'>
    <detector name='3234' label='94/KellogW1' lane='1' field='26.5' controller='ctl_60416'/>
    <detector name='3235' label='94/KellogW2' lane='2' field='25.0' controller='ctl_60416'/>
    <detector name='3236' label='94/KellogW3' lane='3' field='22.6' controller='ctl_60416'/>
  </r_node>
  <r_node name='rnd_87211' n_type='Entrance' transition='Leg' label='Mounds Blvd' lon='-93.07788' lat='44.95477' lanes='1' shift='5'>
    <detector name='3244' label='94/MoundsWP' category='P' controller='ctl_60416'/>
    <detector name='4865' label='94/MoundsWG' category='G'/>
    <detector name='2578' label='94/MoundsWQ1' category='Q' lane='1' controller='ctl_60416'/>
    <detector name='2589' label='94/MoundsWQ2' category='Q' lane='2' controller='ctl_60416'/>
    <meter name='M94W35' lon='-93.07653' lat='44.95557' storage='920'/>
  </r_node>
  <r_node name='rnd_87215' station_id='S790' label='Kittson St' lon='-93.08043' lat='44.95377' lanes='3' shift='5'>
    <detector name='3231' label='94/KittsnW1' lane='1' field='26.0' controller='ctl_60417'/>
    <detector name='3232' label='94/KittsnW2' lane='2' field='24.0' controller='ctl_60417'/>
    <detector name='3233' label='94/KittsnW3' lane='3' field='21.0' controller='ctl_60417'/>
  </r_node>
  <r_node name='rnd_87217' n_type='Entrance' transition='Loop' label='7th St' lon='-93.08169' lat='44.95333' lanes='1' shift='6'>
    <detector name='3230' label='94/7StWM' category='M' field='21.0' controller='ctl_60417'/>
  </r_node>
  <r_node name='rnd_91040' n_type='Entrance' transition='Loop' label='T.H.52 NB' lon='-93.08177' lat='44.9533' lanes='1' shift='6'>
    <detector name='3229' label='94/NB52WM' category='M' controller='ctl_60417'/>
  </r_node>
  <r_node name='rnd_675' label='T.H.52' lon='-93.08427' lat='44.95252' lanes='4' shift='6'/>
  <r_node name='rnd_91042' label='7th St' lon='-93.0858' lat='44.95236' lanes='4' shift='6'/>
  <r_node name='rnd_721' label='7th St' lon='-93.08714' lat='44.95261' lanes='4' shift='6'/>
  <r_node name='rnd_674' label='7th St' lon='-93.08819' lat='44.95311' lanes='4' shift='6'/>
  <r_node name='rnd_87219' n_type='Exit' transition='Leg' label='I-35E CD NB' lon='-93.08925' lat='44.95389' lanes='1' shift='5' forks='rnd_91007'/>
  <r_node name='rnd_87221' n_type='Exit' transition='Leg' label='Jackson St' lon='-93.09018' lat='44.95434' lanes='1' shift='5'>
    <detector name='1896' label='94/JacksnWX' category='X' controller='ctl_1860'/>
  </r_node>
  <r_node name='rnd_87223' station_id='S97' label='I-35E' lon='-93.09098' lat='44.9545' lanes='3' shift='5'>
    <detector name='1897' label='94/35EW1' lane='1' field='29.6' controller='ctl_1860'/>
    <detector name='1898' label='94/35EW2' lane='2' field='29.5' controller='ctl_1860'/>
    <detector name='1899' label='94/35EW3' lane='3' field='25.2' controller='ctl_1860'/>
  </r_node>
  <r_node name='rnd_280' label='I-35E' lon='-93.09261' lat='44.9544' lanes='3' shift='5'/>
  <r_node name='rnd_87225' n_type='Entrance' transition='Leg' label='I-35E SB' lon='-93.09506' lat='44.95316' lanes='2' attach_side='left'/>
  <r_node name='rnd_90827' n_type='Entrance' transition='Leg' label='I-94 CD WB' lon='-93.09596' lat='44.95273' lanes='1' shift='5'/>
  <r_node name='rnd_673' label='Wabasha St' lon='-93.09862' lat='44.95147' lanes='5' shift='5'/>
  <r_node name='rnd_87227' n_type='Exit' transition='Leg' label='I-35E SB' lon='-93.10044' lat='44.95076' lanes='2' attach_side='left' shift='2'/>
  <r_node name='rnd_672' label='John Ireland Blvd' lon='-93.10157' lat='44.95059' lanes='3' shift='5'/>
  <r_node name='rnd_87229' station_id='S500' label='John Ireland Blvd' lon='-93.10329' lat='44.95057' lanes='3' shift='5'>
    <detector name='2490' label='94/JohnIrW1' lane='1' field='30.0' controller='ctl_1811'/>
    <detector name='2491' label='94/JohnIrW2' lane='2' field='30.0' controller='ctl_1811'/>
    <detector name='2492' label='94/JohnIrW3' lane='3' field='26.0' controller='ctl_1811'/>
  </r_node>
  <r_node name='rnd_87233' n_type='Entrance' transition='Leg' label='Wabasha St' lon='-93.10489' lat='44.95074' lanes='1' attach_side='left' shift='2'>
    <detector name='1890' label='94/WabashWP' category='P' field='9.0' controller='ctl_1811'/>
    <detector name='3534' label='94/WabashWQ' category='Q' field='24.0' controller='ctl_1811'/>
    <detector name='4867' label='94/WabashWG' category='G'/>
    <meter name='M94W41' lon='-93.10342' lat='44.95051' storage='1390'/>
  </r_node>
  <r_node name='rnd_87231' n_type='Exit' transition='Leg' label='Marion St' lon='-93.10608' lat='44.95089' lanes='1' shift='5'>
    <detector name='3227' label='94/MarionWX' category='X' controller='ctl_1809'/>
  </r_node>
  <r_node name='rnd_87235' station_id='S546' label='Marion St' lon='-93.11033' lat='44.95093' lanes='3' shift='5'>
    <detector name='2653' label='94/MarionW1' lane='1' field='26.3' controller='ctl_1810'/>
    <detector name='2654' label='94/MarionW2' lane='2' field='30.0' controller='ctl_1810'/>
    <detector name='2655' label='94/MarionW3' lane='3' field='27.0' controller='ctl_1810'/>
  </r_node>
  <r_node name='rnd_87237' n_type='Entrance' transition='Leg' label='5th St' lon='-93.11214' lat='44.95101' lanes='1' shift='6'>
    <detector name='3228' label='94/5StWM' category='M' controller='ctl_1810'/>
  </r_node>
  <r_node name='rnd_87239' n_type='Entrance' transition='Leg' label='Marion St' lon='-93.11352' lat='44.9511' lanes='1' shift='6'>
    <detector name='2593' label='94/MarionWQ' category='Q' field='18.0' controller='ctl_1810'/>
    <detector name='2656' label='94/MarionWP' category='P' controller='ctl_1810'/>
    <detector name='2657' label='94/MarionWB' category='B' controller='ctl_1810'/>
    <detector name='4868' label='94/MarionWG' category='G'/>
    <meter name='M94W43' lon='-93.11181' lat='44.95128' storage='350'/>
  </r_node>
  <r_node name='rnd_87243' n_type='Exit' transition='Leg' label='Dale St' lon='-93.12312' lat='44.95184' lanes='1' shift='6'>
    <detector name='3226' label='94/DaleWX' category='X' controller='ctl_1807'/>
  </r_node>
  <r_node name='rnd_87245' station_id='S789' label='Dale St' lon='-93.1267' lat='44.95187' lanes='4' shift='6'>
    <detector name='6987' label='94/DaleWO' category='O' controller='ctl_1807'/>
    <detector name='3222' label='94/DaleW1' lane='1' field='26.7' controller='ctl_1808'/>
    <detector name='3223' label='94/DaleW2' lane='2' field='29.8' controller='ctl_1808'/>
    <detector name='3224' label='94/DaleW3' lane='3' field='32.7' controller='ctl_1808'/>
    <detector name='3225' label='94/DaleW4' lane='4' field='29.4' controller='ctl_1808'/>
  </r_node>
  <r_node name='rnd_87247' n_type='Entrance' transition='Leg' label='Dale St' lon='-93.13395' lat='44.95185' lanes='1' shift='6'>
    <detector name='2594' label='94/DaleWQ' category='Q' controller='ctl_1808'/>
    <detector name='2658' label='94/DaleWP' category='P' controller='ctl_1808'/>
    <detector name='4869' label='94/DaleWG' category='G'/>
    <meter name='M94W44' lon='-93.13102' lat='44.95205' storage='1304'/>
  </r_node>
  <r_node name='rnd_87249' station_id='S788' label='Victoria St' lon='-93.13689' lat='44.95183' lanes='4' shift='6'>
    <detector name='6985' label='94/VictorWO' category='O' controller='ctl_2026'/>
    <detector name='3218' label='94/VictorW1' lane='1' field='31.0' controller='ctl_2026'/>
    <detector name='3219' label='94/VictorW2' lane='2' field='28.0' controller='ctl_2026'/>
    <detector name='3220' label='94/VictorW3' lane='3' field='31.4' controller='ctl_2026'/>
    <detector name='3221' label='94/VictorW4' lane='4' field='26.0' controller='ctl_2026'/>
  </r_node>
  <r_node name='rnd_87251' n_type='Exit' transition='Leg' label='Lexington Ave' lon='-93.14197' lat='44.95181' lanes='1' shift='6'>
    <detector name='3217' label='94/LexngtWX' category='X' controller='ctl_1805'/>
  </r_node>
  <r_node name='rnd_87253' station_id='S548' label='Lexington Ave' lon='-93.14888' lat='44.95177' lanes='4' shift='6'>
    <detector name='6983' label='94/LexngtWO' category='O' controller='ctl_1806'/>
    <detector name='2663' label='94/LexngtW1' lane='1' field='29.5' controller='ctl_1806'/>
    <detector name='2664' label='94/LexngtW2' lane='2' field='30.3' controller='ctl_1806'/>
    <detector name='2665' label='94/LexngtW3' lane='3' field='33.0' controller='ctl_1806'/>
    <detector name='2666' label='94/LexngtW4' lane='4' field='26.3' controller='ctl_1806'/>
  </r_node>
  <r_node name='rnd_87255' n_type='Entrance' transition='Leg' label='Lexington Ave' lon='-93.15035' lat='44.95179' lanes='1' shift='6'>
    <detector name='2595' label='94/LexngtWQ' category='Q' controller='ctl_1806'/>
    <detector name='2667' label='94/LexngtWP' category='P' controller='ctl_1806'/>
    <detector name='4870' label='94/LexngtWG' category='G'/>
    <meter name='M94W45' lon='-93.14893' lat='44.95201' storage='466'/>
  </r_node>
  <r_node name='rnd_87257' n_type='Exit' transition='Leg' label='Hamline Ave' lon='-93.15318' lat='44.95186' lanes='1' shift='6'>
    <detector name='3216' label='94/HamlinWX' category='X' controller='ctl_2024'/>
  </r_node>
  <r_node name='rnd_87259' station_id='S787' label='Hamline Ave' lon='-93.1564' lat='44.95183' lanes='4' shift='6'>
    <detector name='3212' label='94/HamlinWA1' category='A' lane='1' field='28.0' controller='ctl_2024'/>
    <detector name='3213' label='94/HamlinW2' lane='2' field='30.8' controller='ctl_2024'/>
    <detector name='3214' label='94/HamlinW3' lane='3' field='30.0' controller='ctl_2024'/>
    <detector name='3215' label='94/HamlinW4' lane='4' field='27.0' controller='ctl_2024'/>
  </r_node>
  <r_node name='rnd_87261' n_type='Exit' transition='Leg' label='Snelling Ave' lon='-93.16205' lat='44.95178' lanes='1' shift='5'>
    <detector name='3211' label='94/SnelngWX' category='X' controller='ctl_1803'/>
  </r_node>
  <r_node name='rnd_87263' station_id='S549' label='Snelling Ave' lon='-93.16994' lat='44.95183' lanes='3' shift='5'>
    <detector name='6980' label='94/SnelngWO' category='O' controller='ctl_1804'/>
    <detector name='2668' label='94/SnelngW1' lane='1' field='55.0' controller='ctl_1804'/>
    <detector name='2669' label='94/SnelngW2' lane='2' field='54.0' controller='ctl_1804'/>
    <detector name='2670' label='94/SnelngW3' lane='3' controller='ctl_1804'/>
  </r_node>
  <r_node name='rnd_87265' n_type='Entrance' transition='Leg' label='Snelling Ave' lon='-93.17088' lat='44.95184' lanes='1' shift='6'>
    <detector name='2500' label='94/SnelngWB' category='B' controller='ctl_1804'/>
    <detector name='2596' label='94/SnelngWQ' category='Q' controller='ctl_1804'/>
    <detector name='2671' label='94/SnelngWP' category='P' controller='ctl_1804'/>
    <detector name='4871' label='94/SnelngWG' category='G'/>
    <meter name='M94W46' lon='-93.16981' lat='44.95199' storage='552'/>
  </r_node>
  <r_node name='rnd_671' label='W of Snelling Ave' lon='-93.17796' lat='44.95198' lanes='4' shift='6'/>
  <r_node name='rnd_87269' station_id='S786' label='Prior Ave' lon='-93.18185' lat='44.95283' lanes='4' shift='6'>
    <detector name='6979' label='94/PriorWO' category='O' controller='ctl_2023'/>
    <detector name='3207' label='94/PriorWA1' category='A' lane='1' field='24.0' controller='ctl_2023'/>
    <detector name='3208' label='94/PriorW2' lane='2' field='32.0' controller='ctl_2023'/>
    <detector name='3209' label='94/PriorW3' lane='3' field='25.5' controller='ctl_2023'/>
    <detector name='3210' label='94/PriorW4' lane='4' field='23.5' controller='ctl_2023'/>
  </r_node>
  <r_node name='rnd_87271' n_type='Exit' transition='Leg' label='Vandalia St' lon='-93.18916' lat='44.9552' lanes='1' shift='6'>
    <detector name='3206' label='94/VandalWX' category='X' controller='ctl_1801'/>
  </r_node>
  <r_node name='rnd_87273' station_id='S550' label='Vandalia St' lon='-93.19464' lat='44.95712' lanes='4' shift='6'>
    <detector name='6976' label='94/VandalWO' category='O' controller='ctl_1802'/>
    <detector name='2672' label='94/VandalWA1' category='A' lane='1' field='24.0' controller='ctl_1802'/>
    <detector name='2673' label='94/VandalW2' lane='2' field='28.0' controller='ctl_1802'/>
    <detector name='2674' label='94/VandalW3' lane='3' field='26.0' controller='ctl_1802'/>
    <detector name='2675' label='94/VandalW4' lane='4' field='21.0' controller='ctl_1802'/>
  </r_node>
  <r_node name='rnd_87275' n_type='Entrance' transition='Leg' label='Vandalia St' lon='-93.19611' lat='44.95765' lanes='1' shift='6'>
    <detector name='2623' label='94/VandalWM-ABND' abandoned='t' category='M'/>
    <detector name='2699' label='94/VandalWP' category='P' controller='ctl_1802'/>
    <detector name='2700' label='94/VandalWB' category='B' controller='ctl_1802'/>
    <detector name='4872' label='94/VandalWG' category='G'/>
    <detector name='7061' label='94/VandalW'/>
    <detector name='7062' label='94/VandalW'/>
    <detector name='7063' label='94/VandalW' controller='ctl_1802'/>
    <detector name='7064' label='94/VandalW' controller='ctl_1802'/>
    <detector name='3527' label='94/VandalWQ1' category='Q' lane='1' controller='ctl_1802'/>
    <detector name='3528' label='94/VandalWQ2' category='Q' lane='2' controller='ctl_1802'/>
    <meter name='M94W47' lon='-93.19514' lat='44.9575' storage='818'/>
  </r_node>
  <r_node name='rnd_670' label='E of T.H.280' lon='-93.19795' lat='44.95842' lanes='4' shift='6'/>
  <r_node name='rnd_87279' n_type='Exit' transition='Leg' label='T.H.280 NB' lon='-93.20091' lat='44.96' lanes='1' shift='5' forks='rnd_94155'>
    <detector name='3203' label='94/NB280WX' category='X' controller='ctl_1800'/>
  </r_node>
  <r_node name='rnd_669' label='T.H.280' lon='-93.20294' lat='44.96041' lanes='3' shift='5'/>
  <r_node name='rnd_87281' station_id='S551' label='T.H.280' lon='-93.20487' lat='44.96027' lanes='3' shift='5'>
    <detector name='2676' label='94/280W1' lane='1' field='28.5' controller='ctl_1800'/>
    <detector name='2677' label='94/280W2' lane='2' field='30.5' controller='ctl_1800'/>
    <detector name='2678' label='94/280W3' lane='3' field='28.7' controller='ctl_1800'/>
    <detector name='7036' label='94/280W4' lane='4'/>
  </r_node>
  <r_node name='rnd_668' label='T.H.280' lon='-93.20716' lat='44.96009' lanes='3' shift='5'/>